package orchestrator

import (
	"sync"

	"github.com/go-appsec/secagent/agent"
)

// WorkerDecision captures the director's decision for one worker, made
// via a single decide_worker tool call. Exactly one decision per alive
// worker per iter (by construction of the per-worker decision loop).
type WorkerDecision struct {
	Kind             string // continue | expand | stop
	WorkerID         int
	Instruction      string // required for continue/expand
	Reason           string // required for stop
	AutonomousBudget int    // 1..20; 0 → defaultAutonomousBudget at apply time
	// Fork, when non-nil, means the director also wants to spawn a child
	// worker that inherits this worker's chronicle. Carried alongside the
	// main action so the per-worker decision can be "expand and also fork
	// a child onto a permutation" in one tool call.
	Fork *ForkSubAction
}

// ForkSubAction is the optional fork sub-decision attached to a
// WorkerDecision. NewWorkerID must not collide with any taken id (alive
// or completed) — validated at the tool-handler boundary.
type ForkSubAction struct {
	NewWorkerID int
	Instruction string
}

// PlanEntry is one element of a plan_workers call (synthesis phase only).
type PlanEntry struct {
	WorkerID   int
	Assignment string
}

// CompletedWorker is the durable record of a worker retired during the run.
// Summary is generated by SummarizeCompletedWorker (asynchronously via
// RetireQueue) and applied to the director chat in place via
// DirectorChat.ReplaceWorkerWithSummary; this struct also keeps a
// controller-side registry so synthesis logging and ID-collision guards
// can see the historical roster.
type CompletedWorker struct {
	ID        int
	StoppedAt int    // iteration when the worker was retired
	Reason    string // explicit director reason, "stall-force-stop", or empty
	Summary   string // detailed third-person recap of the worker's full investigation
}

// FindingFiled is a verifier-filed finding.
type FindingFiled struct {
	Title                  string
	Severity               string
	Endpoint               string
	Description            string
	ReproductionSteps      string
	Evidence               string
	Impact                 string
	VerificationNotes      string
	SupersedesCandidateIDs []string
	FollowUpHint           string
}

// CandidateDismissal records a dismissal.
type CandidateDismissal struct {
	CandidateID  string
	Reason       string
	FollowUpHint string
}

// DecisionQueue holds cross-phase orchestrator tool-call state.
//
// Decision phase (per-worker decide_worker calls) populates
// WorkerDecisions one entry at a time, each tied to a specific worker
// asked about. Synthesis phase populates Plan, EndRunSummary, or
// DirectionDoneSummary.
type DecisionQueue struct {
	mu                      sync.Mutex
	Plan                    []PlanEntry
	HasPlan                 bool
	WorkerDecisions         []WorkerDecision
	Findings                []FindingFiled
	Dismissals              []CandidateDismissal
	EndRunSummary           string
	HasEndRun               bool
	VerificationDoneSummary string
	HasVerificationDone     bool
	DirectionDoneSummary    string
	HasDirectionDone        bool
	phase                   agent.Phase
	// askedWorkerID is the worker_id the current per-worker decision
	// prompt asked about. Set by BeginPerWorkerDecision; checked by the
	// decide_worker handler so the director can't decide a different
	// worker than asked.
	askedWorkerID int
}

// NewDecisionQueue creates an idle queue.
func NewDecisionQueue() *DecisionQueue {
	return &DecisionQueue{phase: agent.PhaseIdle}
}

// Reset clears all iteration-scoped state.
func (q *DecisionQueue) Reset() {
	q.mu.Lock()
	defer q.mu.Unlock()
	q.Plan, q.HasPlan = nil, false
	q.WorkerDecisions = nil
	q.Findings = nil
	q.Dismissals = nil
	q.EndRunSummary, q.HasEndRun = "", false
	q.VerificationDoneSummary, q.HasVerificationDone = "", false
	q.DirectionDoneSummary, q.HasDirectionDone = "", false
	q.phase = agent.PhaseIdle
	q.askedWorkerID = 0
}

// BeginPhase transitions into a phase and clears only that phase's done flag.
func (q *DecisionQueue) BeginPhase(p agent.Phase) {
	q.mu.Lock()
	defer q.mu.Unlock()
	q.phase = p
	switch p {
	case agent.PhaseVerification:
		q.VerificationDoneSummary = ""
		q.HasVerificationDone = false
	case agent.PhaseDirection:
		q.DirectionDoneSummary = ""
		q.HasDirectionDone = false
	}
}

// Phase returns the current phase.
func (q *DecisionQueue) Phase() agent.Phase {
	q.mu.Lock()
	defer q.mu.Unlock()
	return q.phase
}

// BeginPerWorkerDecision records which worker_id the next decide_worker
// call is allowed to target. Calling decide_worker with a different
// worker_id rejects with a clear error so the model can retry. Pass
// workerID=0 to disable the check (used outside the per-worker loop).
func (q *DecisionQueue) BeginPerWorkerDecision(workerID int) {
	q.mu.Lock()
	defer q.mu.Unlock()
	q.askedWorkerID = workerID
}

// AskedWorkerID returns the worker_id the current decision prompt asked
// about (0 when no per-worker decision is in flight).
func (q *DecisionQueue) AskedWorkerID() int {
	q.mu.Lock()
	defer q.mu.Unlock()
	return q.askedWorkerID
}

// SetPlan overwrites the current plan.
func (q *DecisionQueue) SetPlan(entries []PlanEntry) {
	q.mu.Lock()
	defer q.mu.Unlock()
	q.Plan = append(q.Plan[:0], entries...)
	q.HasPlan = true
}

// AddDecision records a per-worker decision.
func (q *DecisionQueue) AddDecision(d WorkerDecision) {
	q.mu.Lock()
	defer q.mu.Unlock()
	q.WorkerDecisions = append(q.WorkerDecisions, d)
}

// AddFinding records a filed finding.
func (q *DecisionQueue) AddFinding(f FindingFiled) {
	q.mu.Lock()
	defer q.mu.Unlock()
	q.Findings = append(q.Findings, f)
}

// AddDismissal records a dismissal.
func (q *DecisionQueue) AddDismissal(d CandidateDismissal) {
	q.mu.Lock()
	defer q.mu.Unlock()
	q.Dismissals = append(q.Dismissals, d)
}

// SetEndRun signals run end.
func (q *DecisionQueue) SetEndRun(summary string) {
	q.mu.Lock()
	defer q.mu.Unlock()
	q.EndRunSummary = summary
	q.HasEndRun = true
}

// SetVerificationDone marks the verification phase complete.
func (q *DecisionQueue) SetVerificationDone(summary string) {
	q.mu.Lock()
	defer q.mu.Unlock()
	q.VerificationDoneSummary = summary
	q.HasVerificationDone = true
}

// SetDirectionDone marks the direction phase complete.
func (q *DecisionQueue) SetDirectionDone(summary string) {
	q.mu.Lock()
	defer q.mu.Unlock()
	q.DirectionDoneSummary = summary
	q.HasDirectionDone = true
}
